import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {Box, Button, Card, Container, Paper} from "@mui/material";
import Link from 'next/link'

const Home: NextPage = () => {
  return (
    <Box sx={{ paddingTop: 4 }}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', flex: 1 }}>
        <Paper sx={{ backgroundColor: '#fff', padding: 2, minHeight: 300, display: 'flex', flexDirection: 'column', justifyContent: 'center' }} elevation={2}>
          <Link href="/task1">
            <Button color="primary" variant="outlined" sx={{ margin: 2 }}>
              Моделирование процесса финансирования совместного проекта
            </Button>
          </Link>
          <Link href="/task2">
            <Button color="primary" variant="outlined" sx={{ margin: 2 }}>
              Моделирование процесса распределения портфеля заказов
            </Button>
          </Link>
        </Paper>
      </Container>
    </Box>
  )
}

export default Home
